name:                wreq-play
version:             0.1.0.0
github:              "githubuser/wreq-play"
license:             BSD3
author:              "Daniel Rolls"
maintainer:          "example@example.com"
copyright:           "2020 Daniel Rolls"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wreq-play#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- foldl
- github
- http-client
- lens
- lens-aeson
- process
- servant
- servant-client
- sort
- text
- turtle
- wreq

library:
  source-dirs: src

executables:
  wreq-play-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wreq-play

tests:
  wreq-play-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wreq-play
