name:                haskellpunch
version:             0.1.0.0
github:              "danielrolls/hyterminal"
license:             GPL3
author:              "Daniel Rolls"
maintainer:          "daniel.rolls.27@googlemail.com"
copyright:           "2020 Daniel Rolls"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://danielrolls/hyterminal>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- foldl
- http-client
- lens
- lens-aeson
- pager
- process
- sort
- text
- turtle
- unordered-containers
- wreq

library:
  source-dirs: []

executables:
  haskell-punch--exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellpunch
